### PR TITLE
refactor: switch to `typed_builder`

### PR DESCRIPTION
**Pull request by ansg191**

### CODE REVIEW

**Comment by Veetaha** [comment]
Hi @ansg191, I found this PR via the dependency graph in GitHub. Is there anything about bon in particular that made you switch to typed builder? 👀 I'm asking, because I want to improve that in bon.

UPD: I suppose it's the `diagnostic::on_unimplemented` attribute that was stabilized in 1.78. I'm planning to add a low MSRV requirement for `bon` in one of the coming releases (`2.2.0` or `2.2.1`). It means this attribute will become conditioned upon the rust version, and so compatibility with the older `rustc` won't be a problem: https://github.com/elastio/bon/issues/81. As for the other lints caused by generated code I'll add the `#[automatically_derived]/#[allow]` attributed to fix those as well internally.

**Comment by Veetaha** [comment]
UPD: I've released the patch version of `bon` that fixes the accidental lints leaking from the generated code here and sets the initial MSRV to `1.70.0`. Note that we plan to lower the MSRV even more in the future, but this first attempt at lowering it to `1.70.0` is already good enough and useful, so the decision was made to release it as a new patch.

**Comment by ansg191** [comment]
Hi, @Veetaha

I was just about to write to you about some of the problems I faced with (namely the lints and the MSRV), but it seems that you've fixed them already in elastio/bon#101. I've been personally working with crate dependencies on many projects that are unmaintained for months, so seeing these problems addressed so quickly is nice to see.

Personally, I think `bon` is the best builder generator I have worked with. The documentation is well made and simple and the defaults are exactly how I expect and want them to be.

The only problem left I have is mostly a cosmetic one: for a struct, I don't want to use an *attribute macro*. I understand why it is necessary for function builders, and using the same interface for functions and structs makes `bon` very clean. 

However, sometimes attribute macros cause problems in syntax highlighting, autocomplete, and performance with IDEs that do macro expansion (e.g. RustRover). There isn't anything `bon` can really do about this, its more of an IDE problem. Derive macros don't really have this problem because they can't change the struct definition, so IDEs handle them better.

RustRover fails to highlight struct fields and figure out usages with attribute macro:

image
image

VSCode didn't seem to have any problems in my quick testing.

Finally, because derive macros **can't** modify the struct definition, it makes me a lot more confident to use it without breakage. I'm sure `bon` won't break/change struct definitions and it may seem like a small thing, but it is one less thing I have to worry or think about when looking at a `bon`ified struct.

I haven't looked into the `bun-macros` code, so I don't know if it is trivial to accomplish, but a `bon::Builder` derive macro would be great in alleviating some of these problems.

Thanks for reaching out and fixing many of these issues so quickly. Like I said earlier, `bon` is by far the best builder generator out there, and it is just small annoyances like lints and IDE issues that have prevented me from fully jumping onboard.

**Comment by Veetaha** [comment]
Thank you for the feedback! I see the problem here. I'm using VSCode + Rust Analyzer and I haven't noticed such a problem. I'll look closer into the Rust Rover side of that. Maybe there is indeed something in the code generated by `bon` that poses problems for the Rust Rover. For example, the tokens span information getting mixed up.

I created https://github.com/elastio/bon/issues/104 to do the further research. I see the need for a derive version of the macro even more. Maybe `bon` will just expose that as well. I don't like the API duality that it may bring, so unless I find what's wrong in the Rust Rover there I'll think of adding derive API

**Comment by Veetaha** [comment]
Btw. is this specific to `bon`, or do you see such problems in Rust Rover with other attribute macros like `#[async_trait]`, `#[pin_project]` or `#[tracing::instrument]`?

**Comment by ansg191** [comment]
So `#[pin_project]` works, but that is because `pin_project` uses a derive macro as its internal.

image

**Comment by Veetaha** [comment]
Yeah, `#[pin_project]`'s internal derive approach was something I've been looking into doing as well. Thank you for sharing this.

**Comment by ansg191** [comment]
And as for `#[async_trait]` and `#[tracing::instrument]`, they work, but I highly suspect RustRover is doing some internal hard-coded sneakiness for those specific macros to avoid expanding them.

image

image

**Comment by Veetaha** [comment]
I doubt that, but who knows. Maybe it's just the order in which `bon` places the generated items. For example, if I place the struct right at the beginning of the expansion, this may fix the problem. I'll experiment with this. Thank you for looking into this though!

**Pull request merged**
